name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-macos:
    name: Build macOS Release
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    
    - name: Build Release
      run: swift build -c release --product gemini-cli
    
    - name: Create macOS binary
      run: |
        cp .build/release/gemini-cli ./gemini-cli-macos
        chmod +x ./gemini-cli-macos
        tar -czf gemini-cli-macos.tar.gz gemini-cli-macos
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: gemini-cli-macos
        path: gemini-cli-macos.tar.gz

  build-linux:
    name: Build Linux Release
    runs-on: ubuntu-latest
    container:
      image: swift:5.9-jammy
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl libcurl4-openssl-dev
    
    - name: Build Release
      run: swift build -c release --product gemini-cli
    
    - name: Create Linux binary
      run: |
        cp .build/release/gemini-cli ./gemini-cli-linux
        chmod +x ./gemini-cli-linux
        tar -czf gemini-cli-linux.tar.gz gemini-cli-linux
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: gemini-cli-linux
        path: gemini-cli-linux.tar.gz

  create-release:
    name: Create GitHub Release
    needs: [build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        files: |
          gemini-cli-macos/gemini-cli-macos.tar.gz
          gemini-cli-linux/gemini-cli-linux.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}